In [12]:
import pandas as pd
import ast

In [14]:
df = pd.read_csv('./data/annotated/full_ner/all_annotations_minimal_fixed_multi.csv')
df['tokens'] = df['tokens'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
df['ner_tags'] = df['ner_tags'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
df['annotations_tuples'] = df['annotations_tuples'].apply(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

In [24]:

# Create a list to hold the new rows
rows = []

for _, row in df.iterrows():
    doc_id = row['doc_id']
    
    for s_idx, e_idx, ent_type, ent_text in row['annotations_tuples']:
        if ent_type in ("age", "weight"):
            new_row = {
                'doc_id': doc_id,
                'ent_type': ent_type,
                'ent_text': ent_text,
                's_idx': s_idx,
                'e_idx': e_idx
            }
            rows.append(new_row)

# Create the new DataFrame
new_df = pd.DataFrame(rows)
new_df['doc_id_unique'] = new_df['doc_id'].astype(str) + "_" + new_df['s_idx'].astype(str) + "_" + new_df['e_idx'].astype(str)

In [26]:
new_df

,doc_id,ent_type,ent_text,s_idx,e_idx,doc_id_unique
0,My_pdf931_method,weight,Fifty male Sprague Dawley rats weighing 250 gr...,171,280,My_pdf931_method_171_280
1,My_pdf69new_method,age,All animal studies were performed in male New ...,34,219,My_pdf69new_method_34_219
2,My_pdf69new_method,weight,All animal studies were performed in male New ...,34,219,My_pdf69new_method_34_219
3,My_pdf764_method,age,Adult male SD rats (180-200 g) provided by the...,46,295,My_pdf764_method_46_295
4,My_pdf764_method,weight,Adult male SD rats (180-200 g) provided by the...,46,295,My_pdf764_method_46_295
...,...,...,...,...,...,...
1004,My_pdf475new_method,age,Female Brown Norway (BN) rats 8-10 weeks of ag...,31,107,My_pdf475new_method_31_107
1005,My_pdf411new_method,weight,Experiments were performed on adult male Sprag...,41,187,My_pdf411new_method_41_187
1006,My_pdf411new_method,age,Experiments were performed on adult male Sprag...,41,187,My_pdf411new_method_41_187
1007,My_pdf726_method,age,This 3-day study used a total of 36 randomized...,393,461,My_pdf726_method_393_461
1008,My_pdf325new_method,weight,A total of 50 male Sprague-Dawley (SD) rats wi...,334,459,My_pdf325new_method_334_459

In [28]:
# Get unique doc_id_unique per entity type
age_docs = set(new_df[new_df['ent_type'] == 'age']['doc_id_unique'].unique())
weight_docs = set(new_df[new_df['ent_type'] == 'weight']['doc_id_unique'].unique())

# Intersect to find docs with both
both_docs = age_docs & weight_docs

# Print results
print("Unique with age:", len(age_docs))
print("Unique with weight:", len(weight_docs))
print("Unique with both:", len(both_docs))

Unique with age: 486
Unique with weight: 523
Unique with both: 190

In [36]:
new_df_age = new_df[new_df['ent_type']=='age']
new_df_age

,doc_id,ent_type,ent_text,s_idx,e_idx,doc_id_unique
1,My_pdf69new_method,age,All animal studies were performed in male New ...,34,219,My_pdf69new_method_34_219
3,My_pdf764_method,age,Adult male SD rats (180-200 g) provided by the...,46,295,My_pdf764_method_46_295
5,My_pdf484new_method,age,"For all experiments described, larvae from 0 t...",1068,1157,My_pdf484new_method_1068_1157
8,My_pdf238new_method,age,Experiments were carried out in a double-blind...,28,219,My_pdf238new_method_28_219
9,My_pdf737_method,age,The experiments were performed on adult (10-12...,47,178,My_pdf737_method_47_178
...,...,...,...,...,...,...
1001,My_pdf690_method,age,"Forty adult, clean, female, Sprague-Dawley rat...",54,250,My_pdf690_method_54_250
1003,My_pdf801_method,age,Female adult (10 weeks old) C57BL/6J mice were...,65,158,My_pdf801_method_65_158
1004,My_pdf475new_method,age,Female Brown Norway (BN) rats 8-10 weeks of ag...,31,107,My_pdf475new_method_31_107
1006,My_pdf411new_method,age,Experiments were performed on adult male Sprag...,41,187,My_pdf411new_method_41_187
1007,My_pdf726_method,age,This 3-day study used a total of 36 randomized...,393,461,My_pdf726_method_393_461

In [38]:
new_df_age.to_csv("data/age_annotations.csv")

In [34]:
new_df_weight = new_df[new_df['ent_type']=='weight']
new_df_weight.to_csv("data/weight_annotations.csv")