In [4]:
import pandas as pd

# drug

In [5]:
preclinical_drugs="/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/04_normalization/data/mapped_all/mapped_preclinical_drug_data_with_umls_parents.csv"
df_drugs_pre = pd.read_csv(preclinical_drugs)
df_drugs_pre.shape

(540999, 11)

In [6]:
doc_id_col = "PMID"
drug_raw_entities_col = "unique_interventions_linkbert_predictions"

drug_linked_entities_col = "drug_umls_term_norm"
drug_linked_entities_ids = "drug_umls_termid"

drug_parent_entities_col = "nearest_dataset_parent_umls_label"
drug_with_parents_entities_col = "merged_umls_label"
drug_with_parents_entities_ids = "merged_umls_termid"

cols_to_keep = [
    doc_id_col,
    drug_raw_entities_col,
    drug_linked_entities_col,
    drug_linked_entities_ids,
    drug_parent_entities_col,
    drug_with_parents_entities_col,
    drug_with_parents_entities_ids,
]

df_to_analyse_drug_preclin = df_drugs_pre[cols_to_keep].copy()
df_to_analyse = df_to_analyse_drug_preclin.copy()
df_to_analyse.head()

,PMID,unique_interventions_linkbert_predictions,drug_umls_term_norm,drug_umls_termid,nearest_dataset_parent_umls_label,merged_umls_label,merged_umls_termid
0,31733831,isorhynchophylline,isorhynchophylline,C0245133,-1,isorhynchophylline,C0245133
1,31733833,mir-1192|antgomir-1192|agomir-1192,"MIRN1192 microRNA, mouse|antgomir-1192|agomir-...",C3849422|-1|-1,-1,"MIRN1192 microRNA, mouse|antgomir-1192|agomir-...",C3849422|-1|-1
2,31733925,hla-g2|g2,HLA-G2 Isoform|g2,C0967254|-1,-1,HLA-G2 Isoform|g2,C0967254|-1
3,31733940,minocycline,Minocycline,C0026187,-1,Minocycline,C0026187
4,31734027,tadalafil|phosphodiesterase type 5 inhibitor t...,Tadalafil|Tadalafil,C1176316|C1176316,-1,Tadalafil,C1176316

# disease

In [7]:
preclinical_disesases = "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/04_normalization/data/mapped_all/mapped_preclinical_data_mondo_cleaned_with_mondo_parents.csv"
df_dis_pre = pd.read_csv(preclinical_disesases)
df_dis_pre.shape

(540999, 13)

In [8]:
doc_id_col = "PMID"
disease_raw_entities_col = "unique_conditions_linkbert_predictions"

disease_linked_entities_col = "disease_mondo_term_norm"
disease_linked_entities_ids = "disease_mondo_termid"

cleaned_mondo_entities = "disease_term_mondo_clean"

disease_parent_entities_col = "nearest_dataset_parent_label"
disease_with_parents_entities_col = "merged_mondo_label"
disease_with_parents_entities_ids = "merged_mondo_termid"

cols_to_keep = [
    doc_id_col,
    disease_raw_entities_col,
    disease_linked_entities_col,
    disease_linked_entities_ids,
    cleaned_mondo_entities,
    disease_parent_entities_col,
    disease_with_parents_entities_col,
    disease_with_parents_entities_ids,
]
df_to_analyse_disease_preclin = df_dis_pre[cols_to_keep].copy()
df_to_analyse = df_to_analyse_disease_preclin.copy()
df_to_analyse.head()

,PMID,unique_conditions_linkbert_predictions,disease_mondo_term_norm,disease_mondo_termid,disease_term_mondo_clean,nearest_dataset_parent_label,merged_mondo_label,merged_mondo_termid
0,31733831,asthma,asthma,MONDO:0004979,asthma,-1,asthma,MONDO:0004979
1,31733833,myocardial infarction,myocardial infarction,MONDO:0005068,myocardial infarction,-1,myocardial infarction,MONDO:0005068
2,31733925,systemic lupus erythematosus,systemic lupus erythematosus,MONDO:0007915,systemic lupus erythematosus,-1,systemic lupus erythematosus,MONDO:0007915
3,31733940,cognitive impairment,cognitive disorder,MONDO:0002039,cognitive disorder,-1,cognitive disorder,MONDO:0002039
4,31734027,cumulative peripheral neuropathy|oxaliplatin-i...,cumulative peripheral neuropathy|oxaliplatin-i...,-1|-1|MONDO:0003620,cumulative peripheral neuropathy|oxaliplatin-i...,-1,cumulative peripheral neuropathy|oxaliplatin-i...,-1|-1|MONDO:0003620

In [10]:
df_to_analyse[df_to_analyse['PMID']==8719407]

,PMID,unique_conditions_linkbert_predictions,disease_mondo_term_norm,disease_mondo_termid,disease_term_mondo_clean,nearest_dataset_parent_label,merged_mondo_label,merged_mondo_termid
468923,8719407,dependent diabetes,type 1 diabetes mellitus,MONDO:0005147,type 1 diabetes mellitus,-1,type 1 diabetes mellitus,MONDO:0005147

# merge and save

In [11]:
df_to_analyse_preclin = df_to_analyse_disease_preclin.merge(df_to_analyse_drug_preclin, on="PMID")

In [12]:
df_to_analyse_preclin.to_csv("data/entities_drug_disease_preclin.csv", index=False)

In [13]:
df_to_analyse_preclin.to_csv("/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/04_normalization/data/mapped_all/entities_drug_disease_preclin.csv", index=False)