In [1]:
import sys
sys.path.append("../04_normalization")   # adjust path to your real folder
from neural_based_nen import main
import pandas as pd

In [2]:
data_dir =  "/shares/animalwelfare.crs.uzh/Preclinical_Pipeline/04_normalization/data/"

In [8]:
input_file = "./data/diseases_dictionary_mesh_icd_manual_flat_20260224.csv"
neuro_diseases = pd.read_csv(input_file)
neuro_diseases.head()

,Neurological Disease,Source,Disease Class
0,"1-methyl-4-phenyl-1,2,3,6-tetrahydropyridine i...",ICD,Diseases of the nervous system
1,11p Partial Monosomy Syndrome,MeSH,Neurologic Manifestations
2,"3s, Spinocerebellar Ataxia",MeSH,Neurodegenerative Diseases
3,"47,XX,+21",MeSH,Neurologic Manifestations
4,"47,XY,+21",MeSH,Neurologic Manifestations

In [16]:
mapping_type = "disease"
col_to_map = "Neurological Disease"
output_file = "/scratch/sdonev/Preclinical_Pipeline/10_use_case_disease_focus/out/diseases_dictionary_mesh_icd_manual_flat_20260224_mapped.csv"

main(mapping_type, col_to_map, data_dir, input_file, output_file, stats_dir=None)

Input file: ./data/diseases_dictionary_mesh_icd_manual_flat_20260224.csv

/home/sdonev/.local/lib/python3.11/site-packages/huggingface_hub/file_download.py:896: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

Using terminology: mondo
Using distance threshold: 9.65
Starting normalization for: DISEASE with cdist 9.65
Loading embeddings from /shares/animalwelfare.crs.uzh/Preclinical_Pipeline/04_normalization/data/mondo/embeddings with prefix MONDO_emb...
Loading term-id pairs from /shares/animalwelfare.crs.uzh/Preclinical_Pipeline/04_normalization/data/mondo/mondo_term_id_pairs.json...
No COMBINED embeddings file found, loading all batch files...
Loaded embeddings: torch.Size([129189, 768]), term_id_pairs: 129189, canonical mappings: 30084
Found 18854 unique terms in 'Neurological Disease'

Embedding unique terms: 100%|██████████| 148/148 [07:49<00:00,  3.17s/it]
Mapping Neurological Disease NER to mondo: 100%|██████████| 18875/18875 [00:01<00:00, 10583.40it/s]

Normalization time for 'Neurological Disease': 0:07:51
Output saved to: /scratch/sdonev/Preclinical_Pipeline/10_use_case_disease_focus/out/diseases_dictionary_mesh_icd_manual_flat_20260224_mapped.csv

In [23]:
mapped = pd.read_csv(output_file)
mapped = pd.concat([mapped, neuro_diseases[['Disease Class']]], axis=1)
mapped = mapped.drop_duplicates(subset="disease_mondo_term_norm")
mapped.head()

,Neurological Disease,linkbert_mondo_Neurological Disease,disease_mondo_termid,disease_mondo_term_norm,disease_mondo_closest_3,disease_mondo_cdist,Disease Class
0,"1-methyl-4-phenyl-1,2,3,6-tetrahydropyridine i...","1-methyl-4-phenyl-1,2,3,6-tetrahydropyridine i...",-1,"1-methyl-4-phenyl-1,2,3,6-tetrahydropyridine i...","[['CO-induced parkinsonism', 'MONDO:0017639'],...",11.6223,Diseases of the nervous system
1,11p Partial Monosomy Syndrome,11p partial monosomy syndrome,MONDO:0008681,WAGR syndrome,"[['11p partial monosomy syndrome', 'MONDO:0008...",0.0078,Neurologic Manifestations
2,"3s, Spinocerebellar Ataxia",spinocerebellar ataxia type 3,MONDO:0007182,Machado-Joseph disease,"[['spinocerebellar ataxia type 3', 'MONDO:0007...",5.6338,Neurodegenerative Diseases
3,"47,XX,+21","47,XX,+21",-1,"47,XX,+21","[['47,XXX', 'MONDO:0018066'], ['47,XXY syndrom...",9.7818,Neurologic Manifestations
4,"47,XY,+21","47,XYY",MONDO:0019339,"47,XYY syndrome","[['47,XYY', 'MONDO:0019339'], ['47, XYY syndro...",9.0507,Neurologic Manifestations

In [25]:
mapped[['disease_mondo_term_norm','disease_mondo_termid','Disease Class']].to_csv("./data/list_neuro_conditions.csv",index=False)