In [246]:
import requests
from bs4 import BeautifulSoup
import xml.etree.ElementTree as ET
import pandas as pd
import re
from tqdm import tqdm
import urllib.parse
import spacy
import scispacy
import time

In [515]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
from bs4 import BeautifulSoup
import time

### should be a pre-processing step before age classification
-> only for mice??

In [110]:
df_age = pd.read_csv("./model_predictions/age/age_unsloth_meta_llama_3.1_8b_doc_level_predictions.csv")

# Step 1: Filter out ranges (e.g., "8-14 weeks" or "3–4 months")
def is_range(age_str):
    return bool(re.search(r"\d+\s*[-–]\s*\d+", str(age_str)))  # includes hyphen and en-dash

df_age = df_age[
    (~df_age['prediction_encoded_label'].apply(is_range)) &
    (df_age['age_prediction'].str.contains('weeks', case=False, na=False))
].copy()

df_age.head()

       PMID   age_prediction  supporting_sentence_ids prediction_encoded_label
0  10229113        810 weeks               10229113_1                810 weeks
1  10372527         68 weeks               10372527_0                 68 weeks
2  10405874         60 weeks               10405874_9                 60 weeks
4  10536012         89 weeks               10536012_0                 89 weeks
7  10613826  46 weeks, adult  10613826_0; 10613826_21          46 weeks, adult

In [112]:
# Step 2: Split comma-separated age strings into multiple rows
df_age['prediction_encoded_label'] = df_age['prediction_encoded_label'].astype(str)
df_flat = df_age.assign(
    prediction_encoded_label_flat=df_age['prediction_encoded_label'].str.split(',')
).explode('prediction_encoded_label_flat')

df_flat.head(10)

,PMID,age_prediction,supporting_sentence_ids,prediction_encoded_label,prediction_encoded_label_flat
0,10229113,810 weeks,10229113_1,810 weeks,810 weeks
1,10372527,68 weeks,10372527_0,68 weeks,68 weeks
2,10405874,60 weeks,10405874_9,60 weeks,60 weeks
4,10536012,89 weeks,10536012_0,89 weeks,89 weeks
7,10613826,"46 weeks, adult",10613826_0; 10613826_21,"46 weeks, adult",46 weeks
7,10613826,"46 weeks, adult",10613826_0; 10613826_21,"46 weeks, adult",adult
9,10696912,68 weeks,10696912_9,68 weeks,68 weeks
11,10814783,58 weeks,10814783_1,58 weeks,58 weeks
14,10869055,68 weeks,10869055_0,68 weeks,68 weeks
15,10900333,8 weeks,10900333_5,8 weeks,8 weeks

In [114]:
# Step 3: Clean whitespace
df_flat['prediction_encoded_label_flat'] = df_flat['prediction_encoded_label_flat'].str.strip()

# Step 4: Split into age_num and age_time
split_cols = df_flat['prediction_encoded_label_flat'].str.split(" ", n=1, expand=True)
df_flat['age_num'] = pd.to_numeric(split_cols[0], errors='coerce')
df_flat['age_time'] = split_cols[1].str.lower()  # Normalize unit
df_flat.head()

,PMID,age_prediction,supporting_sentence_ids,prediction_encoded_label,prediction_encoded_label_flat,age_num,age_time
0,10229113,810 weeks,10229113_1,810 weeks,810 weeks,810.0,weeks
1,10372527,68 weeks,10372527_0,68 weeks,68 weeks,68.0,weeks
2,10405874,60 weeks,10405874_9,60 weeks,60 weeks,60.0,weeks
4,10536012,89 weeks,10536012_0,89 weeks,89 weeks,89.0,weeks
7,10613826,"46 weeks, adult",10613826_0; 10613826_21,"46 weeks, adult",46 weeks,46.0,weeks

### Fix clearly invalid ranges

In [117]:
df_age_to_validate_age_too_high = df_flat[df_flat['age_num'] > 150]
df_age_to_validate_age_too_high

,PMID,age_prediction,supporting_sentence_ids,prediction_encoded_label,prediction_encoded_label_flat,age_num,age_time
0,10229113,810 weeks,10229113_1,810 weeks,810 weeks,810.0,weeks
16,10900347,"712 weeks, 8 weeks",10900347_22; 10900347_29; 10900347_37,"712 weeks, 8 weeks",712 weeks,712.0,weeks
30,11217864,812 weeks,11217864_27; 11217864_3,812 weeks,812 weeks,812.0,weeks
44,11859145,710 weeks,11859145_6,710 weeks,710 weeks,710.0,weeks
52,12020957,816 weeks,12020957_1,816 weeks,816 weeks,816.0,weeks
...,...,...,...,...,...,...,...
2161,38885894,810 weeks,38885894_2,810 weeks,810 weeks,810.0,weeks
2169,38996350,612 weeks,38996350_28; 38996350_32,612 weeks,612 weeks,612.0,weeks
2172,39046528,810 weeks,39046528_0; 39046528_156; 39046528_159; 390465...,810 weeks,810 weeks,810.0,weeks
2180,39142423,814 weeks,39142423_4,814 weeks,814 weeks,814.0,weeks
2197,39260333,810 weeks,39260333_1,810 weeks,810 weeks,810.0,weeks

In [119]:
def normalize_age(age_str):
    if not age_str:
        return age_str
    
    parts = age_str.split()
    if len(parts) == 2:
        age, unit = parts
    else:
        return age_str  # Leave unchanged if not in expected format

    if "-" not in age:
        try:
            age_float = float(age)
            if age_float > 150:
                if len(age) == 3:
                    age = f"{age[0]}-{age[1:]}"
                else:
                    age = f"{age[:2]}-{age[2:]}"
        except ValueError:
            return age_str  # Not a number, leave it unchanged

    return f"{age} {unit}"

# Apply the logic
df_age_to_validate_age_too_high["prediction_encoded_label_new"] = df_age_to_validate_age_too_high["prediction_encoded_label_flat"].apply(normalize_age)
df_age_to_validate_age_too_high

/var/folders/nd/2fzvhsh510gbt9x6z5pdb1gr0000gn/T/ipykernel_82621/2005132760.py:25: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_age_to_validate_age_too_high["prediction_encoded_label_new"] = df_age_to_validate_age_too_high["prediction_encoded_label_flat"].apply(normalize_age)

,PMID,age_prediction,supporting_sentence_ids,prediction_encoded_label,prediction_encoded_label_flat,age_num,age_time,prediction_encoded_label_new
0,10229113,810 weeks,10229113_1,810 weeks,810 weeks,810.0,weeks,8-10 weeks
16,10900347,"712 weeks, 8 weeks",10900347_22; 10900347_29; 10900347_37,"712 weeks, 8 weeks",712 weeks,712.0,weeks,7-12 weeks
30,11217864,812 weeks,11217864_27; 11217864_3,812 weeks,812 weeks,812.0,weeks,8-12 weeks
44,11859145,710 weeks,11859145_6,710 weeks,710 weeks,710.0,weeks,7-10 weeks
52,12020957,816 weeks,12020957_1,816 weeks,816 weeks,816.0,weeks,8-16 weeks
...,...,...,...,...,...,...,...,...
2161,38885894,810 weeks,38885894_2,810 weeks,810 weeks,810.0,weeks,8-10 weeks
2169,38996350,612 weeks,38996350_28; 38996350_32,612 weeks,612 weeks,612.0,weeks,6-12 weeks
2172,39046528,810 weeks,39046528_0; 39046528_156; 39046528_159; 390465...,810 weeks,810 weeks,810.0,weeks,8-10 weeks
2180,39142423,814 weeks,39142423_4,814 weeks,814 weeks,814.0,weeks,8-14 weeks
2197,39260333,810 weeks,39260333_1,810 weeks,810 weeks,810.0,weeks,8-10 weeks

### Work with PMCID

In [521]:
# Compiled regex pattern for week-related age expressions
age_keywords_pattern = r"""
\b(
    age|ages|aged|aging|old|older|young|adult|adults|senescent|
    neonatal|neonate|newborn|pup|pups|juvenile|weanling|weaning|
    postnatal|prenatal|prepubescent|fetal|fetus|fetuses|
    week[-\s]?old|weekold|                         # forms like "week-old", "weekold"
    \d+\s*(?:-|–|to)\s*\d+\s*(week|wk)s?\b|             # range: e.g., "6–8 weeks"
    \d+\s*(week|wk)s?(?!\s*old)|                   # standalone: e.g., "8 weeks" but not "8 weeks old"
    after\s+birth|post[-\s]?birth
)\b
"""

# Compile the pattern once
_age_week_regex = re.compile(age_keywords_pattern, flags=re.IGNORECASE | re.VERBOSE)

def contains_week_age_expression(text: str) -> bool:
    """
    Returns True if the text contains a week-related age expression, else False.
    """
    return bool(_age_week_regex.search(text))

In [523]:
contains_week_age_expression("The mature miR-146a (primer catalog #000468, Applied Biosystems) was normalized against the expression of U6 snRNA as an endogenous normalization control in tissue samples, while the synthetic spike-in control (cel–miR-39 mimic; Qiagen) for internal normalization in plasma samples.")

False

In [122]:
df_age_to_validate = df_flat[(df_flat['age_num'] > 40) & (df_flat['age_num'] < 150)]
df_age_to_validate

,PMID,age_prediction,supporting_sentence_ids,prediction_encoded_label,prediction_encoded_label_flat,age_num,age_time
1,10372527,68 weeks,10372527_0,68 weeks,68 weeks,68.0,weeks
2,10405874,60 weeks,10405874_9,60 weeks,60 weeks,60.0,weeks
4,10536012,89 weeks,10536012_0,89 weeks,89 weeks,89.0,weeks
7,10613826,"46 weeks, adult",10613826_0; 10613826_21,"46 weeks, adult",46 weeks,46.0,weeks
9,10696912,68 weeks,10696912_9,68 weeks,68 weeks,68.0,weeks
...,...,...,...,...,...,...,...
2168,38980500,68 weeks,38980500_0; 38980500_102; 38980500_105; 389805...,68 weeks,68 weeks,68.0,weeks
2173,39053427,68 weeks,39053427_4,68 weeks,68 weeks,68.0,weeks
2212,39489122,69 weeks,39489122_16; 39489122_3,69 weeks,69 weeks,69.0,weeks
2264,9916140,"56 weeks, 68 weeks",9916140_18; 9916140_34; 9916140_46; 9916140_6,"56 weeks, 68 weeks",56 weeks,56.0,weeks
2264,9916140,"56 weeks, 68 weeks",9916140_18; 9916140_34; 9916140_46; 9916140_6,"56 weeks, 68 weeks",68 weeks,68.0,weeks

In [124]:
EMAIL = "donevasimona@gmail.com"  # Your email for NCBI API access

def pmid_to_pmcid(pmid):
    url = (
        f"https://www.ncbi.nlm.nih.gov/pmc/utils/idconv/v1.0/"
        f"?tool=fulltext-fetcher&email={EMAIL}&ids={pmid}&format=json"
    )
    try:
        r = requests.get(url)
        data = r.json()
        records = data.get("records", [])
        if records and "pmcid" in records[0]:
            return records[0]["pmcid"]
    except Exception as e:
        print(f"  Error converting PMID {pmid}: {e}")
    return None

In [126]:
tqdm.pandas()
df_age_to_validate['PMCID'] = df_age_to_validate['PMID'].progress_apply(pmid_to_pmcid)
df_age_to_validate

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 172/172 [01:24<00:00,  2.05it/s]
/var/folders/nd/2fzvhsh510gbt9x6z5pdb1gr0000gn/T/ipykernel_82621/2942715007.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_age_to_validate['PMCID'] = df_age_to_validate['PMID'].progress_apply(pmid_to_pmcid)

,PMID,age_prediction,supporting_sentence_ids,prediction_encoded_label,prediction_encoded_label_flat,age_num,age_time,PMCID
1,10372527,68 weeks,10372527_0,68 weeks,68 weeks,68.0,weeks,None
2,10405874,60 weeks,10405874_9,60 weeks,60 weeks,60.0,weeks,None
4,10536012,89 weeks,10536012_0,89 weeks,89 weeks,89.0,weeks,PMC23131
7,10613826,"46 weeks, adult",10613826_0; 10613826_21,"46 weeks, adult",46 weeks,46.0,weeks,None
9,10696912,68 weeks,10696912_9,68 weeks,68 weeks,68.0,weeks,None
...,...,...,...,...,...,...,...,...
2168,38980500,68 weeks,38980500_0; 38980500_102; 38980500_105; 389805...,68 weeks,68 weeks,68.0,weeks,PMC12052871
2173,39053427,68 weeks,39053427_4,68 weeks,68 weeks,68.0,weeks,None
2212,39489122,69 weeks,39489122_16; 39489122_3,69 weeks,69 weeks,69.0,weeks,None
2264,9916140,"56 weeks, 68 weeks",9916140_18; 9916140_34; 9916140_46; 9916140_6,"56 weeks, 68 weeks",56 weeks,56.0,weeks,PMC407886
2264,9916140,"56 weeks, 68 weeks",9916140_18; 9916140_34; 9916140_46; 9916140_6,"56 weeks, 68 weeks",68 weeks,68.0,weeks,PMC407886

In [142]:
df_age_to_validate_with_pmc = df_age_to_validate[df_age_to_validate['PMCID'].notna()].copy()
df_age_to_validate_with_pmc.shape

(26, 8)

In [144]:
df_age_to_validate_with_pmc.to_csv("./model_predictions/age/post_processing/df_age_to_validate_with_pmc.csv", index=False)

In [590]:
df_age_to_validate_with_pmc = pd.read_csv("./model_predictions/age/post_processing/df_age_to_validate_with_pmc.csv")

In [592]:
df_age_to_validate_with_pmc.head()

,PMID,age_prediction,supporting_sentence_ids,prediction_encoded_label,prediction_encoded_label_flat,age_num,age_time,PMCID
0,10536012,89 weeks,10536012_0,89 weeks,89 weeks,89.0,weeks,PMC23131
1,12531880,"4 weeks, 68 weeks",12531880_19; 12531880_35; 12531880_46; 12531880_8,"4 weeks, 68 weeks",68 weeks,68.0,weeks,PMC151876
2,18003831,67 weeks,18003831_0,67 weeks,67 weeks,67.0,weeks,PMC6673319
3,19282478,"6 weeks, 78 weeks, 910 weeks",19282478_0; 19282478_23; 19282478_3,"6 weeks, 78 weeks, 910 weeks",78 weeks,78.0,weeks,PMC2664014
4,19850890,48 weeks,19850890_3,48 weeks,48 weeks,48.0,weeks,PMC2789629

In [594]:
def normalize_dashes(text: str) -> str:
    # Replace en dash (–), em dash (—), and minus (−) with regular hyphen (-)
    return re.sub(r"[–—−]", "-", text)

In [596]:
nlp = spacy.load("en_core_sci_sm")

In [713]:
def resolve_age_from_text(age_text_to_check: str, current_age: str, current_age_time: str) -> str:
    """
    Detects if current_age (e.g., "68") is in the text. If not, tries to detect if it was misparsed from a range like "6–8".
    Returns the matched form, or original fallback if not found.
    """
    # 1. Try common valid forms for the age
    patterns = [
        rf'\b{current_age}\b(?!\s*[%\w])',                                # e.g. 56 but NOT 56%, 56001, 56n
        rf'\b{current_age}\s*(weeks?|wks?)\b(?!\s*%)',                    # e.g. 56 weeks, not 56% weeks
        rf'\b{current_age}[-\s]?(weeks?|wks?)[-\s]?old\b(?!\s*%)',        # e.g. 56-week-old
    ]
    for pattern in patterns:
        if re.search(pattern, age_text_to_check, flags=re.IGNORECASE):
            return f"{current_age} {current_age_time}"

    # 2. Try to catch range forms like "6–8"
    if len(current_age) == 2:
        a, b = current_age[0], current_age[1]
        range_pattern = rf'\b{a}[-–]{b}(?=\s|[-–]?(weeks?|wks?)\b)'
        match = re.search(range_pattern, age_text_to_check)
        if match:
            return f"{a}-{b} {current_age_time}"

    # 3. Fallback
    return f"{current_age} {current_age_time}"


def process_row(row):
    pmcid = row['PMCID']
    current_age = str(int(row['age_num']))
    current_age_time = row['age_time']

    url = f"https://www.ncbi.nlm.nih.gov/pmc/articles/{pmcid}/"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
    }

    try:
        response = requests.get(url, headers=headers, timeout=10)
        if response.status_code != 200:
            return None  # Or: return row['prediction_encoded_label']

        soup = BeautifulSoup(response.text, "html.parser")

        age_sentences = []

        for section in soup.find_all("section"):
            heading = section.find(["h2", "h3", "h4"])
            heading_text = heading.get_text(strip=True) if heading else "No heading"
            if heading_text in ["Abstract", "Results", "Discussion", "Abbreviations"]:
                continue

            for p in section.find_all("p"):
                doc = nlp(p.get_text(strip=True))
                for sent in doc.sents:
                    sentence_text = sent.text.strip()
                    #label, _ = age_clf.classify(sentence_text)
                    if contains_week_age_expression(sentence_text):
                        age_sentences.append(sentence_text)

        age_text_to_check = normalize_dashes(' '.join(age_sentences))
        corrected_label = resolve_age_from_text(age_text_to_check, current_age, current_age_time)

        return corrected_label

    except Exception as e:
        print(f"Error processing {pmcid}: {e}")
        return None

In [600]:
resolve_age_from_text("C57Bl/6 and SJL/J mice (6–8 weeks old) were obtained from Jackson Laboratory (Bar Harbor, ME, USA).", "68", "weeks")

'6–8 weeks'

In [566]:
df_age_to_validate_with_pmc["prediction_encoded_label_new"] = df_age_to_validate_with_pmc.progress_apply(process_row, axis=1)

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26/26 [01:08<00:00,  2.63s/it]

In [567]:
df_age_to_validate_with_pmc

,PMID,age_prediction,supporting_sentence_ids,prediction_encoded_label,prediction_encoded_label_flat,age_num,age_time,PMCID,prediction_encoded_label_new
0,10536012,89 weeks,10536012_0,89 weeks,89 weeks,89.0,weeks,PMC23131,8–9 weeks
1,12531880,"4 weeks, 68 weeks",12531880_19; 12531880_35; 12531880_46; 12531880_8,"4 weeks, 68 weeks",68 weeks,68.0,weeks,PMC151876,6–8 weeks
2,18003831,67 weeks,18003831_0,67 weeks,67 weeks,67.0,weeks,PMC6673319,6–7 weeks
3,19282478,"6 weeks, 78 weeks, 910 weeks",19282478_0; 19282478_23; 19282478_3,"6 weeks, 78 weeks, 910 weeks",78 weeks,78.0,weeks,PMC2664014,78 weeks
4,19850890,48 weeks,19850890_3,48 weeks,48 weeks,48.0,weeks,PMC2789629,4–8 weeks
5,19850918,56 weeks,19850918_0,56 weeks,56 weeks,56.0,weeks,PMC2794761,5–6 weeks
6,21555855,68 weeks,21555855_6; 21555855_75,68 weeks,68 weeks,68.0,weeks,PMC3104755,6–8 weeks
7,22028844,"72 weeks, 8 weeks",22028844_0; 22028844_11,"72 weeks, 8 weeks",72 weeks,72.0,weeks,PMC3197632,72 weeks
8,24973214,"68 weeks, 810 weeks",24973214_2; 24973214_3,"68 weeks, 810 weeks",68 weeks,68.0,weeks,PMC4132791,6–8 weeks
9,25183005,68 weeks,25183005_6,68 weeks,68 weeks,68.0,weeks,PMC4200254,68 weeks
10,25297853,46 weeks,25297853_192; 25297853_205; 25297853_218; 2529...,46 weeks,46 weeks,46.0,weeks,PMC4389758,4–6 weeks
11,26822306,58 weeks,26822306_0,58 weeks,58 weeks,58.0,weeks,PMC4914792,5–8 weeks
12,28474276,"68 weeks, approximately 68 weeks",28474276_105; 28474276_112; 28474276_119; 2847...,"68 weeks, approximately 68 weeks",68 weeks,68.0,weeks,PMC11877320,6–8 weeks
13,28776347,"11 weeks, 80 days",28776347_4; 28776347_7,"11 weeks, 80 days",80 days,80.0,days,PMC5546971,80 days
14,28945200,68 weeks,28945200_0; 28945200_5,68 weeks,68 weeks,68.0,weeks,PMC5663358,6–8 weeks
15,29497878,68 weeks,29497878_2; 29497878_48; 29497878_53; 29497878_7,68 weeks,68 weeks,68.0,weeks,PMC11481852,6–8 weeks
16,31620963,78 weeks,31620963_0; 31620963_44,78 weeks,78 weeks,78.0,weeks,PMC6895294,7–8 weeks
17,33410109,"68 weeks, 8 weeks",33410109_160; 33410109_191; 33410109_45; 33410...,"68 weeks, 8 weeks",68 weeks,68.0,weeks,PMC8116375,6–8 weeks
18,33426702,68 weeks,33426702_0,68 weeks,68 weeks,68.0,weeks,PMC8062990,6–8 weeks
19,33480040,68 weeks,33480040_9,68 weeks,68 weeks,68.0,weeks,PMC8114201,6–8 weeks
20,34159538,"67 weeks, 8 weeks",34159538_100; 34159538_105; 34159538_200; 3415...,"67 weeks, 8 weeks",67 weeks,67.0,weeks,PMC8608985,6–7 weeks
21,35553640,46 weeks,35553640_0,46 weeks,46 weeks,46.0,weeks,PMC9113142,4–6 weeks
22,36229601,"78 weeks, 78 weeks, adult, adult",36229601_11; 36229601_205; 36229601_208; 36229...,"78 weeks, adult",78 weeks,78.0,weeks,PMC10043010,7–8 weeks
23,38980500,68 weeks,38980500_0; 38980500_102; 38980500_105; 389805...,68 weeks,68 weeks,68.0,weeks,PMC12052871,6–8 weeks
24,9916140,"56 weeks, 68 weeks",9916140_18; 9916140_34; 9916140_46; 9916140_6,"56 weeks, 68 weeks",56 weeks,56.0,weeks,PMC407886,5–6 weeks
25,9916140,"56 weeks, 68 weeks",9916140_18; 9916140_34; 9916140_46; 9916140_6,"56 weeks, 68 weeks",68 weeks,68.0,weeks,PMC407886,6–8 weeks

### Work with Elsevier

In [568]:
def starts_with_cap_block(text, min_length=20):
    """
    Checks if the text starts with a block of ≥ `min_length` consecutive uppercase letters.

    Args:
        text (str): The input text.
        min_length (int): Minimum number of capital letters to consider a match.

    Returns:
        bool: True if it starts with ≥ `min_length` uppercase letters, False otherwise.
    """
    match = re.match(rf'^[A-Z]{{{min_length},}}', text.strip())
    return bool(match)

def is_reference_line(text):
    """
    Determines whether a line resembles a citation or reference entry.

    Args:
        text (str): A line or text chunk.

    Returns:
        bool: True if it's likely a reference, False otherwise.
    """
    text = text.strip()

    # Common: Number + year + page numbers (e.g., "825 1999 189 193")
    if re.search(r'\b\d{3,4}\s+\d{4}\s+\d{2,4}\s+\d{2,4}\b', text):
        return True

    # Contains "et al." + year
    if re.search(r'\bet al\.,?\s+\d{4}', text):
        return True

    # 2 or more people with initials, e.g., "J.L. Ferrara P. Morell"
    if len(re.findall(r'\b[A-Z]\.[A-Z]?\.?\s+[A-Z][a-z]+', text)) >= 2:
        return True

    # Journal name or abbreviation at the end (e.g., "Ann.")
    if re.search(r'\b[A-Z][a-z]{1,}\.$', text):
        return True

    # Starts with a number and has a comma-year author pattern
    if re.match(r'\d{3,4}', text) and re.search(r'[A-Z][a-z]+,\s*\d{4}', text):
        return True

    return False

def is_numeric_metadata_line(text):
    """
    Detects lines that are likely metadata or serial data (mostly numbers).

    Args:
        text (str): Input line or chunk.

    Returns:
        bool: True if it's mostly numeric/ID-like, False if not.
    """
    text = text.strip()
    tokens = text.split()

    # Case: starts with "serial" or "JL", followed by mostly digits
    if tokens and tokens[0].lower() in {"serial", "jl"}:
        return True

    # If more than 80% of tokens are numbers
    numeric_tokens = sum(t.isdigit() for t in tokens)
    if len(tokens) > 0 and numeric_tokens / len(tokens) > 0.8:
        return True

    # If there are 5+ number tokens and no verbs or sentence structure
    if numeric_tokens >= 5:
        return True

    return False

In [602]:
df_age_to_validate_no_pmc = df_age_to_validate[~df_age_to_validate['PMCID'].notna()].copy()
df_age_to_validate_no_pmc.head()

,PMID,age_prediction,supporting_sentence_ids,prediction_encoded_label,prediction_encoded_label_flat,age_num,age_time,PMCID
1,10372527,68 weeks,10372527_0,68 weeks,68 weeks,68.0,weeks,None
2,10405874,60 weeks,10405874_9,60 weeks,60 weeks,60.0,weeks,None
7,10613826,"46 weeks, adult",10613826_0; 10613826_21,"46 weeks, adult",46 weeks,46.0,weeks,None
9,10696912,68 weeks,10696912_9,68 weeks,68 weeks,68.0,weeks,None
11,10814783,58 weeks,10814783_1,58 weeks,58 weeks,58.0,weeks,None

In [604]:
def pmid_to_doi(pmid):
    url = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
    params = {
        "db": "pubmed",
        "id": pmid,
        "retmode": "xml"
    }
    response = requests.get(url, params=params)
    if response.status_code != 200:
        print(f"Error fetching PMID {pmid}")
        return None

    root = ET.fromstring(response.content)
    for article_id in root.findall(".//ArticleId"):
        if article_id.attrib.get("IdType") == "doi":
            return article_id.text
    return None

In [606]:
def doi_to_html_url(doi):
    return f"https://doi.org/{doi}"  # Redirects to publisher page

In [608]:
doi_value = pmid_to_doi("10372527")

In [609]:
def get_elsevier_full_text(pii, api_key):
    """
    Fetches the full article text from Elsevier API using the given PII and API key.

    Args:
        pii (str): Publisher Item Identifier for the article.
        api_key (str): Your Elsevier API key.
        current_age (str): Fallback string if retrieval fails.
        current_age_time (str): Fallback string if retrieval fails.

    Returns:
        str: Full article text if successful, otherwise fallback message.
    """
    url = f"https://api.elsevier.com/content/article/pii/{pii}"
    headers = {
        "X-ELS-APIKey": api_key,
        "Accept": "application/json"
    }

    res = requests.get(url, headers=headers)
    if res.status_code != 200:
        return None

    try:
        data = res.json()
        return data['full-text-retrieval-response']['originalText']
    except Exception:
        return None

In [612]:
def extract_springer_article_text(html_text):
    """
    Extracts the main article content from Springer HTML page.

    Args:
        html_text (str): The raw HTML content of the Springer article page.

    Returns:
        str or None: Cleaned article text if found, otherwise None.
    """
    soup = BeautifulSoup(html_text, 'html.parser')
    article_div = soup.find('div', {'class': 'c-article-body'})
    
    if article_div:
        return article_div.get_text(separator='\n', strip=True)
    
    return None

In [614]:
def get_content_with_selenium(url: str, wait_time: int = 5) -> str:
    options = Options()
    options.add_argument("--headless")  # Run in headless mode
    options.add_argument("--disable-gpu")
    options.add_argument("--no-sandbox")
    options.add_argument("--disable-dev-shm-usage")
    options.add_argument("window-size=1920,1080")
    options.add_argument("user-agent=Mozilla/5.0")

    driver = webdriver.Chrome(options=options)
    
    try:
        driver.get(url)
        time.sleep(wait_time)  # Let JS challenge resolve
        page_source = driver.page_source
    finally:
        driver.quit()

    soup = BeautifulSoup(page_source, 'html.parser')
    article_div = soup.find('div', class_='article-body')  # or whatever the body class is
    
    if article_div:
        text = article_div.get_text(separator="\n", strip=True)
        return text
    else:
        return None

In [743]:
def get_normalized_age_from_elsevier(pmid: str, current_age: str, current_age_time: str, api_key: str) -> str:
    """
    Retrieves article text from Elsevier API using PMID, finds age-related sentences,
    and returns a normalized age label like "8-10 week".
    """
   
    # Step 1: Get DOI
    headers = {
        "User-Agent": "Mozilla/5.0 (compatible; DOI-fetcher/1.0; donevasimona@gmail.com)"
    }
    time.sleep(1.5)  # Delay for NCBI API
    doi = pmid_to_doi(pmid)
    if not doi:
        print(f"no doi found for {pmid}")
        return f"{current_age} {current_age_time}"

    # Step 2: Get ScienceDirect redirect URL
    response = requests.get(doi_to_html_url(doi), headers=headers, allow_redirects=True)
    sciencedirect_url = response.url

    # Step 3: Extract PII if possible
    match = re.search(r'/pii/([A-Z0-9]+)', sciencedirect_url)
    
    if not match:
        # Step 4: Get full text directly
        print(f"processing {pmid} with bsoup")
        original_text = extract_springer_article_text(response.text)

        # try with selenium 
        if not original_text:
            print(f"processing {pmid} with selenium {response.url}")
            original_text = get_content_with_selenium(response.url)    
    else:
        # Step 4: Get full text from Elsevier API
        pii = match.group(1)
        print(f"processing  {pmid} with Elsevier {pii}")
        original_text = get_elsevier_full_text(pii, api_key)
        
    if not original_text:
        print(f"no original text found for: {pmid}")
        return f"{current_age} {current_age_time}"

    # Step 5: Extract and classify age-related sentences
    #print(original_text)
    doc = nlp(original_text)
    age_sentences = []

    for sent in doc.sents:
        sentence_text = sent.text.strip()
        if starts_with_cap_block(sentence_text):
            continue
        if is_numeric_metadata_line(sentence_text):
            continue
        #label, _ = age_clf.classify(sentence_text)
        if contains_week_age_expression(sentence_text):
            age_sentences.append(sentence_text)

    # Step 6: Normalize and return
    age_text_to_check = normalize_dashes(' '.join(age_sentences))
    #print(age_text_to_check)
    return resolve_age_from_text(age_text_to_check, current_age, current_age_time)

In [745]:
def load_elsevier_api_key(filepath="api_keys.txt"):
    with open(filepath, "r") as f:
        for line in f:
            if line.startswith("elsevier_api_key_uoz="):
                return line.strip().split("=")[1].strip('"')
    raise ValueError("API key not found in file.")

API_KEY = load_elsevier_api_key("../07_full_text_retrieval/api_keys.txt")

In [747]:
df_age_to_validate_no_pmc["prediction_encoded_label_new"] = df_age_to_validate_no_pmc.progress_apply(
    lambda row: get_normalized_age_from_elsevier(
        pmid=row["PMID"],
        current_age=str(int(row["age_num"])),
        current_age_time=row["age_time"],
        api_key=API_KEY
    ),
    axis=1
)

  0%|                                                                                                                                             | 0/146 [00:00<?, ?it/s]

processing  10372527 with Elsevier S0730725X98002161

  1%|█▊                                                                                                                                   | 2/146 [00:04<04:48,  2.01s/it]

processing  10405874 with Elsevier S0192056199000193

  2%|██▋                                                                                                                                  | 3/146 [00:08<07:39,  3.21s/it]

processing 10613826 with bsoup

  3%|███▋                                                                                                                                 | 4/146 [00:12<07:51,  3.32s/it]

processing  10696912 with Elsevier S0165572899002477

  3%|████▌                                                                                                                                | 5/146 [00:17<08:55,  3.80s/it]

processing  10814783 with Elsevier S0165572899002350

  4%|█████▍                                                                                                                               | 6/146 [00:22<09:43,  4.17s/it]

processing 10869055 with bsoup
processing 10869055 with selenium https://academic.oup.com/brain/article-lookup/doi/10.1093/brain/123.7.1431

  5%|██████▍                                                                                                                              | 7/146 [00:35<16:52,  7.28s/it]

processing  11024530 with Elsevier S0165572800003489

  5%|███████▎                                                                                                                             | 8/146 [00:40<14:33,  6.33s/it]

processing 11402297 with bsoup

  6%|████████▏                                                                                                                            | 9/146 [00:43<12:42,  5.57s/it]

processing  11498258 with Elsevier S0165572801003526

  7%|█████████                                                                                                                           | 10/146 [00:48<12:02,  5.31s/it]

processing  11585623 with Elsevier S0165572801003940

  8%|█████████▉                                                                                                                          | 11/146 [00:53<11:24,  5.07s/it]

processing  11880146 with Elsevier S0165572801004763

  8%|██████████▊                                                                                                                         | 12/146 [00:57<10:52,  4.87s/it]

processing  12098506 with Elsevier S0165572802001212

  9%|███████████▊                                                                                                                        | 13/146 [01:01<10:24,  4.69s/it]

processing  12161035 with Elsevier S0165572802001765

 10%|████████████▋                                                                                                                       | 14/146 [01:06<10:15,  4.66s/it]

processing 12805101 with bsoup
processing 12805101 with selenium https://academic.oup.com/brain/article/126/8/1895/308016

 10%|█████████████▌                                                                                                                      | 15/146 [01:19<15:33,  7.13s/it]

processing  14512144 with Elsevier S0168010203002177

 11%|██████████████▍                                                                                                                     | 16/146 [01:23<13:22,  6.17s/it]

processing  14975595 with Elsevier S0165572803005149

 12%|███████████████▎                                                                                                                    | 17/146 [01:27<11:56,  5.56s/it]

processing 15845917 with bsoup
processing 15845917 with selenium https://joe.bioscientifica.com/view/journals/joe/185/2/1850243.xml

 12%|████████████████▎                                                                                                                   | 18/146 [01:37<14:30,  6.80s/it]

no original text found for: 15845917
processing  15905104 with Elsevier S1053811905002703

 13%|█████████████████▏                                                                                                                  | 19/146 [01:41<12:59,  6.14s/it]

processing  15953683 with Elsevier S0306452205002848

 14%|██████████████████                                                                                                                  | 20/146 [01:46<11:47,  5.62s/it]

processing  16098614 with Elsevier S0165572805002791

 14%|██████████████████▉                                                                                                                 | 21/146 [01:51<11:19,  5.44s/it]

processing  16183034 with Elsevier S000398610500353X

 15%|███████████████████▉                                                                                                                | 22/146 [01:55<10:28,  5.07s/it]

processing  16870269 with Elsevier S0165572806002232

 16%|████████████████████▊                                                                                                               | 23/146 [02:00<10:22,  5.06s/it]

processing 16921176 with bsoup
processing 16921176 with selenium https://academic.oup.com/brain/article-lookup/doi/10.1093/brain/awl213

 16%|█████████████████████▋                                                                                                              | 24/146 [02:14<15:48,  7.77s/it]

processing 16964563 with bsoup

 17%|██████████████████████▌                                                                                                             | 25/146 [02:18<13:23,  6.64s/it]

processing 17079237 with bsoup
processing 17079237 with selenium https://academic.oup.com/jac/article-lookup/doi/10.1093/jac/dkl446

 18%|███████████████████████▌                                                                                                            | 26/146 [02:30<16:29,  8.25s/it]

processing  17161346 with Elsevier S1567576906002256

 18%|████████████████████████▍                                                                                                           | 27/146 [02:34<13:54,  7.02s/it]

processing 17404322 with bsoup
processing 17404322 with selenium https://academic.oup.com/jimmunol/article/178/8/5366/8023637

 19%|█████████████████████████▎                                                                                                          | 28/146 [02:47<17:13,  8.75s/it]

processing  17632037 with Elsevier S1521661607012284

 20%|██████████████████████████▏                                                                                                         | 29/146 [02:51<14:30,  7.44s/it]

processing 17698561 with bsoup
processing 17698561 with selenium https://academic.oup.com/intimm/article-lookup/doi/10.1093/intimm/dxm078

 21%|███████████████████████████                                                                                                         | 30/146 [03:04<17:21,  8.98s/it]

processing  18339308 with Elsevier S0006291X08004440

 21%|████████████████████████████                                                                                                        | 31/146 [03:08<14:26,  7.53s/it]

processing  18346732 with Elsevier S001448860800054X

 22%|████████████████████████████▉                                                                                                       | 32/146 [03:13<12:54,  6.80s/it]

processing 18563891 with bsoup
processing 18563891 with selenium https://pubs.acs.org/doi/10.1021/jm8000554

 23%|█████████████████████████████▊                                                                                                      | 33/146 [03:23<14:25,  7.66s/it]

no original text found for: 18563891
processing  18619983 with Elsevier S0028390808002335

 23%|██████████████████████████████▋                                                                                                     | 34/146 [03:27<12:36,  6.75s/it]

processing  19010295 with Elsevier S1931524408002272

 24%|███████████████████████████████▋                                                                                                    | 35/146 [03:32<11:01,  5.96s/it]

processing  19083996 with Elsevier S0006899308027820

 25%|████████████████████████████████▌                                                                                                   | 36/146 [03:37<10:27,  5.70s/it]

processing  19344957 with Elsevier S0165572809000708

 25%|█████████████████████████████████▍                                                                                                  | 37/146 [03:41<09:42,  5.34s/it]

processing  19428125 with Elsevier S0165572809001374

 26%|██████████████████████████████████▎                                                                                                 | 38/146 [03:47<09:41,  5.38s/it]

processing  19477025 with Elsevier S0165572809001787

 27%|███████████████████████████████████▎                                                                                                | 39/146 [03:52<09:21,  5.25s/it]

processing  19564052 with Elsevier S0165572809002227

 27%|████████████████████████████████████▏                                                                                               | 40/146 [03:56<08:54,  5.04s/it]

processing  19796825 with Elsevier S0165572809003397

 28%|█████████████████████████████████████                                                                                               | 41/146 [04:02<09:06,  5.21s/it]

processing  19879259 with Elsevier S0014488609004324

 29%|█████████████████████████████████████▉                                                                                              | 42/146 [04:07<09:00,  5.19s/it]

processing 19957206 with bsoup

 29%|██████████████████████████████████████▉                                                                                             | 43/146 [04:11<08:16,  4.82s/it]

processing  20034680 with Elsevier S0165572809004809

 30%|███████████████████████████████████████▊                                                                                            | 44/146 [04:16<08:08,  4.79s/it]

processing  20149931 with Elsevier S0165572810000068

 31%|████████████████████████████████████████▋                                                                                           | 45/146 [04:21<08:09,  4.85s/it]

processing 20233106 with bsoup
processing 20233106 with selenium https://www.tandfonline.com/doi/full/10.3109/08923970903338367

 32%|█████████████████████████████████████████▌                                                                                          | 46/146 [04:30<10:36,  6.37s/it]

no original text found for: 20233106
processing  20971186 with Elsevier S1567576910003140

 32%|██████████████████████████████████████████▍                                                                                         | 47/146 [04:35<09:42,  5.89s/it]

processing 21136279 with bsoup

 33%|███████████████████████████████████████████▍                                                                                        | 48/146 [04:40<08:50,  5.42s/it]

processing  21216565 with Elsevier S0896841110001435

 34%|████████████████████████████████████████████▎                                                                                       | 49/146 [04:44<08:29,  5.25s/it]

processing 21233144 with bsoup
processing 21233144 with selenium https://academic.oup.com/brain/article/134/2/571/400493

 34%|█████████████████████████████████████████████▏                                                                                      | 50/146 [05:00<13:21,  8.35s/it]

processing 21459808 with bsoup
processing 21459808 with selenium https://journals.sagepub.com/doi/10.1177/1352458511400476

 35%|██████████████████████████████████████████████                                                                                      | 51/146 [05:11<14:37,  9.24s/it]

no original text found for: 21459808
processing  21473912 with Elsevier S0889159111001103

 36%|███████████████████████████████████████████████                                                                                     | 52/146 [05:16<12:16,  7.84s/it]

processing  21511012 with Elsevier S0306452211003873

 36%|███████████████████████████████████████████████▉                                                                                    | 53/146 [05:21<11:06,  7.17s/it]

processing  21726878 with Elsevier S0022510X11003649

 37%|████████████████████████████████████████████████▊                                                                                   | 54/146 [05:26<09:47,  6.38s/it]

processing 21804021 with bsoup
processing 21804021 with selenium https://academic.oup.com/jimmunol/article/187/5/2336/7974269

 38%|█████████████████████████████████████████████████▋                                                                                  | 55/146 [05:39<12:27,  8.21s/it]

processing  22036952 with Elsevier S0165572811002657

 38%|██████████████████████████████████████████████████▋                                                                                 | 56/146 [05:43<10:46,  7.18s/it]

processing 22407397 with bsoup

 39%|███████████████████████████████████████████████████▌                                                                                | 57/146 [05:48<09:25,  6.36s/it]

processing 22642808 with bsoup
processing 22642808 with selenium https://www.tandfonline.com/doi/full/10.1179/1743132812Y.0000000032

 40%|████████████████████████████████████████████████████▍                                                                               | 58/146 [05:59<11:19,  7.72s/it]

no original text found for: 22642808
processing  22749732 with Elsevier S156757691200183X

 40%|█████████████████████████████████████████████████████▎                                                                              | 59/146 [06:03<09:37,  6.64s/it]

processing 23037326 with bsoup
processing 23037326 with selenium https://academic.oup.com/jnen/article-lookup/doi/10.1097/NEN.0b013e3182724831

 41%|██████████████████████████████████████████████████████▏                                                                             | 60/146 [06:15<11:59,  8.37s/it]

processing  23141166 with Elsevier S0165572812003062

 42%|███████████████████████████████████████████████████████▏                                                                            | 61/146 [06:20<10:21,  7.31s/it]

processing 23232603 with bsoup
processing 23232603 with selenium https://journals.sagepub.com/doi/10.1177/1352458512469698

 42%|████████████████████████████████████████████████████████                                                                            | 62/146 [06:32<12:00,  8.58s/it]

no original text found for: 23232603
processing 23339019 with bsoup

 43%|████████████████████████████████████████████████████████▉                                                                           | 63/146 [06:36<10:10,  7.35s/it]

processing  23352967 with Elsevier S1521661612003075

 44%|█████████████████████████████████████████████████████████▊                                                                          | 64/146 [06:41<08:56,  6.55s/it]

processing  23602714 with Elsevier S0165572813000817

 45%|██████████████████████████████████████████████████████████▊                                                                         | 65/146 [06:46<08:10,  6.05s/it]

processing 23660634 with bsoup
processing 23660634 with selenium https://journals.lww.com/neuroreport/abstract/2013/06190/pertussis_toxin_attenuates_experimental_autoimmune.5.aspx

 45%|███████████████████████████████████████████████████████████▋                                                                        | 66/146 [06:56<10:00,  7.51s/it]

no original text found for: 23660634
processing  23871488 with Elsevier S0165572813001744

 46%|████████████████████████████████████████████████████████████▌                                                                       | 67/146 [07:02<08:56,  6.80s/it]

processing  23958452 with Elsevier S0028390813003547

 47%|█████████████████████████████████████████████████████████████▍                                                                      | 68/146 [07:07<08:15,  6.35s/it]

processing 24258405 with bsoup

 47%|██████████████████████████████████████████████████████████████▍                                                                     | 69/146 [07:12<07:30,  5.85s/it]

processing 24287115 with bsoup
processing 24287115 with selenium https://academic.oup.com/brain/article-lookup/doi/10.1093/brain/awt324

 48%|███████████████████████████████████████████████████████████████▎                                                                    | 70/146 [07:26<10:48,  8.54s/it]

processing  24486709 with Elsevier S0028390814000343

 49%|████████████████████████████████████████████████████████████████▏                                                                   | 71/146 [07:31<09:05,  7.28s/it]

processing  25149432 with Elsevier S0264410X14011293

 49%|█████████████████████████████████████████████████████████████████                                                                   | 72/146 [07:36<08:05,  6.56s/it]

processing  25218987 with Elsevier S0014299914006451

 50%|██████████████████████████████████████████████████████████████████                                                                  | 73/146 [07:41<07:30,  6.17s/it]

processing 25523105 with bsoup

 51%|██████████████████████████████████████████████████████████████████▉                                                                 | 74/146 [07:46<06:59,  5.83s/it]

processing  25576296 with Elsevier S0014480015000039

 51%|███████████████████████████████████████████████████████████████████▊                                                                | 75/146 [07:50<06:21,  5.37s/it]

processing  25680941 with Elsevier S0969996115000182

 52%|████████████████████████████████████████████████████████████████████▋                                                               | 76/146 [07:56<06:21,  5.45s/it]

processing 25810397 with bsoup
processing 25810397 with selenium https://academic.oup.com/jimmunol/article/194/9/4489/7973086

 53%|█████████████████████████████████████████████████████████████████████▌                                                              | 77/146 [08:10<09:09,  7.96s/it]

processing 25859982 with bsoup

 53%|██████████████████████████████████████████████████████████████████████▌                                                             | 78/146 [08:14<07:38,  6.75s/it]

processing  26112377 with Elsevier S022352341530091X

 54%|███████████████████████████████████████████████████████████████████████▍                                                            | 79/146 [08:18<06:50,  6.12s/it]

processing  26133787 with Elsevier S0889159115002329

 55%|████████████████████████████████████████████████████████████████████████▎                                                           | 80/146 [08:25<06:51,  6.23s/it]

processing 26440666 with bsoup

 55%|█████████████████████████████████████████████████████████████████████████▏                                                          | 81/146 [08:29<06:05,  5.62s/it]

processing 26556034 with bsoup

 56%|██████████████████████████████████████████████████████████████████████████▏                                                         | 82/146 [08:34<05:49,  5.46s/it]

processing  26590655 with Elsevier S2211034815001182

 57%|███████████████████████████████████████████████████████████████████████████                                                         | 83/146 [08:39<05:40,  5.40s/it]

processing  26671084 with Elsevier S0022510X1502479X

 58%|███████████████████████████████████████████████████████████████████████████▉                                                        | 84/146 [08:44<05:23,  5.22s/it]

processing  26735612 with Elsevier S1567576915302253

 58%|████████████████████████████████████████████████████████████████████████████▊                                                       | 85/146 [08:52<06:01,  5.92s/it]

processing  26762804 with Elsevier S0306452216000026

 59%|█████████████████████████████████████████████████████████████████████████████▊                                                      | 86/146 [08:56<05:34,  5.57s/it]

processing 26794621 with bsoup

 60%|██████████████████████████████████████████████████████████████████████████████▋                                                     | 87/146 [09:01<05:07,  5.21s/it]

processing  26805386 with Elsevier S0969996116300109

 60%|███████████████████████████████████████████████████████████████████████████████▌                                                    | 88/146 [09:06<04:56,  5.11s/it]

processing 26924461 with bsoup
processing 26924461 with selenium https://pubs.acs.org/doi/10.1021/acs.jmedchem.6b00089

 61%|████████████████████████████████████████████████████████████████████████████████▍                                                   | 89/146 [09:16<06:24,  6.75s/it]

no original text found for: 26924461
processing  27013356 with Elsevier S0889159116300605

 62%|█████████████████████████████████████████████████████████████████████████████████▎                                                  | 90/146 [09:21<05:50,  6.26s/it]

processing  27372916 with Elsevier S1043466616301545

 62%|██████████████████████████████████████████████████████████████████████████████████▎                                                 | 91/146 [09:28<05:44,  6.26s/it]

processing  27373971 with Elsevier S1521661616301383

 63%|███████████████████████████████████████████████████████████████████████████████████▏                                                | 92/146 [09:32<05:14,  5.82s/it]

processing 27443879 with bsoup
processing 27443879 with selenium https://academic.oup.com/jleukbio/article/101/2/507/6933038

 64%|████████████████████████████████████████████████████████████████████████████████████                                                | 93/146 [09:40<05:41,  6.45s/it]

no original text found for: 27443879
processing  27452720 with Elsevier S0028390816303124

 64%|████████████████████████████████████████████████████████████████████████████████████▉                                               | 94/146 [09:49<06:06,  7.04s/it]

processing 27933584 with bsoup

 65%|█████████████████████████████████████████████████████████████████████████████████████▉                                              | 95/146 [09:53<05:20,  6.28s/it]

processing  28040492 with Elsevier S0304394016310059

 66%|██████████████████████████████████████████████████████████████████████████████████████▊                                             | 96/146 [09:57<04:38,  5.57s/it]

processing  28412473 with Elsevier S0939641117304587

 66%|███████████████████████████████████████████████████████████████████████████████████████▋                                            | 97/146 [10:02<04:26,  5.43s/it]

processing  28619431 with Elsevier S2211034817300676

 67%|████████████████████████████████████████████████████████████████████████████████████████▌                                           | 98/146 [10:10<04:54,  6.14s/it]

processing 28646409 with bsoup

 68%|█████████████████████████████████████████████████████████████████████████████████████████▌                                          | 99/146 [10:15<04:30,  5.75s/it]

processing 28686480 with bsoup
processing 28686480 with selenium https://www.tandfonline.com/doi/full/10.1080/08916934.2017.1332185

 68%|█████████████████████████████████████████████████████████████████████████████████████████▋                                         | 100/146 [10:27<05:55,  7.72s/it]

no original text found for: 28686480
processing 28965161 with bsoup

 69%|██████████████████████████████████████████████████████████████████████████████████████████▌                                        | 101/146 [10:33<05:14,  7.00s/it]

processing  29031145 with Elsevier S1567576917303739

 70%|███████████████████████████████████████████████████████████████████████████████████████████▌                                       | 102/146 [10:37<04:37,  6.31s/it]

processing  29287781 with Elsevier S0024320517306823

 71%|████████████████████████████████████████████████████████████████████████████████████████████▍                                      | 103/146 [10:42<04:12,  5.88s/it]

processing 29667130 with bsoup

 71%|█████████████████████████████████████████████████████████████████████████████████████████████▎                                     | 104/146 [10:49<04:15,  6.08s/it]

processing 29687146 with bsoup

 72%|██████████████████████████████████████████████████████████████████████████████████████████████▏                                    | 105/146 [10:53<03:48,  5.56s/it]

processing  29864912 with Elsevier S0753332218309090

 73%|███████████████████████████████████████████████████████████████████████████████████████████████                                    | 106/146 [10:58<03:36,  5.41s/it]

processing 30143908 with bsoup

 73%|████████████████████████████████████████████████████████████████████████████████████████████████                                   | 107/146 [11:05<03:49,  5.90s/it]

processing  30267995 with Elsevier S0165572818302248

 74%|████████████████████████████████████████████████████████████████████████████████████████████████▉                                  | 108/146 [11:11<03:48,  6.02s/it]

processing 30291491 with bsoup

 75%|█████████████████████████████████████████████████████████████████████████████████████████████████▊                                 | 109/146 [11:15<03:14,  5.26s/it]

processing 30666403 with bsoup

 75%|██████████████████████████████████████████████████████████████████████████████████████████████████▋                                | 110/146 [11:20<03:05,  5.14s/it]

processing  30707940 with Elsevier S0969996118303784

 76%|███████████████████████████████████████████████████████████████████████████████████████████████████▌                               | 111/146 [11:25<03:00,  5.16s/it]

processing  30825702 with Elsevier S2211034819301026

 77%|████████████████████████████████████████████████████████████████████████████████████████████████████▍                              | 112/146 [11:29<02:45,  4.88s/it]

processing  31610192 with Elsevier S0024320519308811

 77%|█████████████████████████████████████████████████████████████████████████████████████████████████████▍                             | 113/146 [11:35<02:46,  5.06s/it]

processing  31678404 with Elsevier S0969996119303055

 78%|██████████████████████████████████████████████████████████████████████████████████████████████████████▎                            | 114/146 [11:40<02:41,  5.05s/it]

processing  31778849 with Elsevier S0165572819302206

 79%|███████████████████████████████████████████████████████████████████████████████████████████████████████▏                           | 115/146 [11:45<02:36,  5.04s/it]

processing 32048246 with bsoup

 79%|████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 116/146 [11:50<02:31,  5.04s/it]

processing  32087283 with Elsevier S0969996120300899

 80%|████████████████████████████████████████████████████████████████████████████████████████████████████████▉                          | 117/146 [11:55<02:31,  5.22s/it]

processing 32514862 with bsoup

 81%|█████████████████████████████████████████████████████████████████████████████████████████████████████████▉                         | 118/146 [12:01<02:25,  5.21s/it]

processing  32712065 with Elsevier S0378111920306569

 82%|██████████████████████████████████████████████████████████████████████████████████████████████████████████▊                        | 119/146 [12:06<02:18,  5.12s/it]

processing 32860610 with bsoup

 82%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▋                       | 120/146 [12:10<02:05,  4.84s/it]

processing 32981181 with bsoup
processing 32981181 with selenium https://faseb.onlinelibrary.wiley.com/doi/10.1096/fj.202000861RR

 83%|████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                      | 121/146 [12:25<03:16,  7.86s/it]

no original text found for: 32981181
processing  32991933 with Elsevier S0014488620303198

 84%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                     | 122/146 [12:30<02:52,  7.18s/it]

processing 33245472 with bsoup

 84%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                    | 123/146 [12:35<02:28,  6.46s/it]

processing  33621940 with Elsevier S0161589021000559

 85%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                   | 124/146 [12:40<02:13,  6.05s/it]

processing  33781828 with Elsevier S0024320521003805

 86%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                  | 125/146 [12:44<01:55,  5.50s/it]

processing  34162131 with Elsevier S1567576921003611

 86%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████                  | 126/146 [12:49<01:43,  5.16s/it]

processing  34280490 with Elsevier S0891061821000879

 87%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                 | 127/146 [12:54<01:36,  5.09s/it]

processing 34487326 with bsoup

 88%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                | 128/146 [12:58<01:27,  4.85s/it]

processing 34618622 with bsoup
processing 34618622 with selenium https://www.tandfonline.com/doi/full/10.1080/08923973.2021.1986063

 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋               | 129/146 [13:09<01:56,  6.85s/it]

no original text found for: 34618622
processing  34758400 with Elsevier S1043661821005533

 89%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋              | 130/146 [13:15<01:42,  6.41s/it]

processing  35461109 with Elsevier S1567576922002557

 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌             | 131/146 [13:19<01:28,  5.87s/it]

processing  35688339 with Elsevier S0889159122001556

 90%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍            | 132/146 [13:26<01:23,  6.00s/it]

processing  35872534 with Elsevier S0008874922001058

 91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎           | 133/146 [13:31<01:15,  5.82s/it]

processing 35947794 with bsoup
processing 35947794 with selenium https://pubs.acs.org/doi/10.1021/acschemneuro.1c00826

 92%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏          | 134/146 [13:41<01:25,  7.15s/it]

no original text found for: 35947794
processing  36075147 with Elsevier S0223523422006341

 92%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 135/146 [13:49<01:19,  7.26s/it]

processing  36279665 with Elsevier S1567576922008578

 93%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████         | 136/146 [13:54<01:06,  6.67s/it]

processing 36287356 with bsoup

 94%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉        | 137/146 [13:59<00:56,  6.24s/it]

processing  36702320 with Elsevier S0969996123000293

 95%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊       | 138/146 [14:05<00:47,  5.91s/it]

processing 36805765 with bsoup

 95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋      | 139/146 [14:09<00:38,  5.50s/it]

processing  37030640 with Elsevier S0378517323003563

 96%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌     | 140/146 [14:15<00:34,  5.68s/it]

processing 37581848 with bsoup

 97%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌    | 141/146 [14:20<00:27,  5.44s/it]

processing 37874905 with bsoup
processing 37874905 with selenium https://pubs.acs.org/doi/10.1021/acs.jmedchem.3c01398

 97%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍   | 142/146 [14:30<00:27,  6.84s/it]

no original text found for: 37874905
processing  38155065 with Elsevier S0165572823002539

 98%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎  | 143/146 [14:36<00:19,  6.54s/it]

processing 38411708 with bsoup

 99%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏ | 144/146 [14:41<00:12,  6.23s/it]

processing 38761250 with bsoup

 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████ | 145/146 [14:46<00:05,  5.75s/it]

processing  39053427 with Elsevier S0753332224010722

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 146/146 [14:52<00:00,  5.79s/it]

processing  39489122 with Elsevier S0753332224015397

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 146/146 [14:57<00:00,  6.15s/it]

In [749]:
df_age_to_validate_no_pmc

,PMID,age_prediction,supporting_sentence_ids,prediction_encoded_label,prediction_encoded_label_flat,age_num,age_time,PMCID,prediction_encoded_label_new
1,10372527,68 weeks,10372527_0,68 weeks,68 weeks,68.0,weeks,None,6-8 weeks
2,10405874,60 weeks,10405874_9,60 weeks,60 weeks,60.0,weeks,None,60 weeks
7,10613826,"46 weeks, adult",10613826_0; 10613826_21,"46 weeks, adult",46 weeks,46.0,weeks,None,4-6 weeks
9,10696912,68 weeks,10696912_9,68 weeks,68 weeks,68.0,weeks,None,6-8 weeks
11,10814783,58 weeks,10814783_1,58 weeks,58 weeks,58.0,weeks,None,5-8 weeks
...,...,...,...,...,...,...,...,...,...
2107,38155065,68 weeks,38155065_42,68 weeks,68 weeks,68.0,weeks,None,6-8 weeks
2134,38411708,"68 weeks, 8 weeks",38411708_144; 38411708_149; 38411708_154; 3841...,"68 weeks, 8 weeks",68 weeks,68.0,weeks,None,6-8 weeks
2154,38761250,68 weeks,38761250_174; 38761250_182; 38761250_190; 3876...,68 weeks,68 weeks,68.0,weeks,None,6-8 weeks
2173,39053427,68 weeks,39053427_4,68 weeks,68 weeks,68.0,weeks,None,6-8 weeks
2212,39489122,69 weeks,39489122_16; 39489122_3,69 weeks,69 weeks,69.0,weeks,None,6-9 weeks

In [751]:
len(df_age_to_validate_no_pmc[df_age_to_validate_no_pmc['prediction_encoded_label_flat']==df_age_to_validate_no_pmc['prediction_encoded_label_new']])

17

In [753]:
df_age_to_validate_no_pmc[df_age_to_validate_no_pmc['prediction_encoded_label_flat']==df_age_to_validate_no_pmc['prediction_encoded_label_new']]

,PMID,age_prediction,supporting_sentence_ids,prediction_encoded_label,prediction_encoded_label_flat,age_num,age_time,PMCID,prediction_encoded_label_new
2,10405874,60 weeks,10405874_9,60 weeks,60 weeks,60.0,weeks,None,60 weeks
136,15845917,68 weeks,15845917_15; 15845917_52,68 weeks,68 weeks,68.0,weeks,None,68 weeks
263,18563891,68 weeks,18563891_8,68 weeks,68 weeks,68.0,weeks,None,68 weeks
361,20233106,68 weeks,20233106_26,68 weeks,68 weeks,68.0,weeks,None,68 weeks
416,21233144,79 weeks,21233144_31,79 weeks,79 weeks,79.0,weeks,None,79 weeks
442,21459808,68 weeks,21459808_0,68 weeks,68 weeks,68.0,weeks,None,68 weeks
538,22642808,68 weeks,22642808_0,68 weeks,68 weeks,68.0,weeks,None,68 weeks
596,23232603,68 weeks,23232603_0,68 weeks,68 weeks,68.0,weeks,None,68 weeks
640,23660634,68 weeks,23660634_1; 23660634_18,68 weeks,68 weeks,68.0,weeks,None,68 weeks
835,25576296,68 weeks,25576296_3,68 weeks,68 weeks,68.0,weeks,None,68 weeks
979,26924461,68 weeks,26924461_472,68 weeks,68 weeks,68.0,weeks,None,68 weeks
1018,27443879,68 weeks,27443879_35,68 weeks,68 weeks,68.0,weeks,None,68 weeks
1159,28686480,68 weeks,28686480_39; 28686480_61,68 weeks,68 weeks,68.0,weeks,None,68 weeks
1600,32981181,68 weeks,32981181_37,68 weeks,68 weeks,68.0,weeks,None,68 weeks
1787,34618622,68 weeks,34618622_0,68 weeks,68 weeks,68.0,weeks,None,68 weeks
1906,35947794,68 weeks,35947794_1,68 weeks,68 weeks,68.0,weeks,None,68 weeks
2083,37874905,79 weeks,37874905_15,79 weeks,79 weeks,79.0,weeks,None,79 weeks

In [645]:
def test_text_processing_age(original_text):
    doc = nlp(original_text)
    age_sentences = []
    
    for sent in doc.sents:
        sentence_text = sent.text.strip()
        if starts_with_cap_block(sentence_text):
            continue
        if is_numeric_metadata_line(sentence_text):
            continue
        if contains_week_age_expression(sentence_text):
            age_sentences.append(sentence_text)
            print(sentence_text)

    return " ".join(age_sentences)

In [723]:
pmid = "19796825"
doi = pmid_to_doi(pmid)
if not doi:
    print(f"no doi found for {pmid}")

# Step 2: Get ScienceDirect redirect URL
response = requests.get(doi_to_html_url(doi), headers=headers, allow_redirects=True)
sciencedirect_url = response.url

# Step 3: Extract PII
match = re.search(r'/pii/([A-Z0-9]+)', sciencedirect_url)
if not match:
    print(f"no sciencedirect_url found for {pmid}")

In [725]:
response.url

'https://linkinghub.elsevier.com/retrieve/pii/S0165572809003397'

In [721]:
url = response.url
html = get_html_with_selenium(url)

soup = BeautifulSoup(html, 'html.parser')
article_div = soup.find('div', class_='article-body')  # or whatever the body class is

if article_div:
    original_text = article_div.get_text(separator="\n", strip=True)
    test_text_processing_age(text)
else:
    print("Article body not found.")

Article body not found.

In [727]:
pii = match.group(1)
print("processing ", pii)
original_text = get_elsevier_full_text(pii, API_KEY)

processing  S0165572809003397

In [707]:
#original_text

In [729]:
age_txt = test_text_processing_age(original_text)

Keywords EAE Hsp70 Inflammation NF-κB Oral Triptolide 1 Introduction Approximately 2 million people worldwide, and about 350,000 people in the United States alone have multiple sclerosis (MS), the most common debilitating illness among young adults (Zivadinov et al., 2003).
In brief, 6–7week old SJL/J female mice (Jackson Laboratory, Bar Harbor, ME) were immunized by subcutaneous injection in the right flank with an emulsion containing 150μg proteolipid protein PLP139–151 peptide in complete Freund's adjuvant (CFA) containing 200μg M. tuberculosis.
2.4 Lymph node cells stimulation Lymph node cells (LNCs) were obtained from naïve SJL mice (7weeks old).
2.7 Cell culture The murine macrophage cell line RAW264.7 (American Type Cell Collection, Rockville, MD) was maintained in DMEM (Invitrogen) supplemented with 10% fetal bovine serum and antibiotics, at 37°C in 5% CO2 incubator.

In [731]:
resolve_age_from_text(age_txt, "67", "weeks")

'6-7 weeks'

In [455]:
soup = BeautifulSoup(response.text, 'html.parser')

# Find the main article body (Springer articles often use this class)
article_div = soup.find('div', {'class': 'c-article-body'})

# Extract and clean the text
if article_div:
    article_text = article_div.get_text(separator='\n', strip=True)
    doc = nlp(article_text)
    age_sentences = []

    for sent in doc.sents:
        sentence_text = sent.text.strip()
        #label, _ = age_clf.classify(sentence_text)
        if contains_week_age_expression(sentence_text):
            age_sentences.append(sentence_text)
else:
    print("Article body not found.")

Article body not found.

In [273]:
age_sentences

['MS affects approximately 2.8 million individuals each year and is the leading cause of non-traumatic disability in young and middle-aged people [\n2\n].',
 'EAE Induction and 4-OI Intervention\nEAE was induced in female C57BL/6 mice aged 6–8\xa0weeks.',
 'BV2 Microglia Inflammation Model Induction and 4-OI Intervention\nBV2 microglia were cultivated in Dulbecco’s Modified Eagle Medium supplemented with 10% fetal bovine serum at 37 °C with 5% CO\n2\n.',
 'Article\nPubMed\nGoogle Scholar\nKim, Byung-Chul., Woo-Kwang. Jeon, Hye-Young.',
 'Hahn, Young-Myeong.']